"""Device state, ESP32 wire protocol, and serial integration."""

from .device_state import (
    DeviceState,
    DeviceStateChange,
    DeviceStateError,
    DeviceStateMachine,
    DeviceStateSnapshot,
    InvalidStateTransition,
    PrivacyConstraintError,
)
from .protocol import (
    ButtonEvent,
    DisplayMessage,
    ErrorMessage,
    EventMessage,
    FaceMessage,
    HeartbeatMessage,
    MessageDirection,
    PrivacyMessage,
    SoundMessage,
    StateMessage,
    TouchEvent,
    TouchMessage,
    UserMessage,
    parse_esp32_message,
    parse_json_line,
    serialize_json_line,
    serialize_pi_message,
)
from .serial_client import ESP32SerialClient, SerialClient, SocketTransport

__all__ = [
    "ButtonEvent",
    "DeviceState",
    "DeviceStateChange",
    "DeviceStateError",
    "DeviceStateMachine",
    "DeviceStateSnapshot",
    "DisplayMessage",
    "ESP32SerialClient",
    "ErrorMessage",
    "EventMessage",
    "FaceMessage",
    "HeartbeatMessage",
    "InvalidStateTransition",
    "MessageDirection",
    "PrivacyConstraintError",
    "PrivacyMessage",
    "SerialClient",
    "SoundMessage",
    "SocketTransport",
    "StateMessage",
    "TouchEvent",
    "TouchMessage",
    "UserMessage",
    "parse_esp32_message",
    "parse_json_line",
    "serialize_json_line",
    "serialize_pi_message",
]
